---
- name: site generator
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
  - include_vars:
      file: /home/iberdrola_installer/poc_files_v2/ans_documentation_v2/_data/ans_doc.yml

   - include_vars:
      file: /var/tmp/ans_documentation_v2/_data/ans_doc.yml

  - name: comprobar valores diccionario
    include_role:
      name: jekyll_templates
    with_items: "{{ ansible_objects }}"
 
